name: "Godot Unit Tests"
on:
    push:
        paths:
            - "**.test.gd"
            - "**.tscn"
            - "**.gd"
            - "**.yml"

jobs:
    execute-tests:
        name: Run tests
        runs-on: ubuntu-latest
        container:
            image: barichello/godot-ci:4.2.1
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  lfs: true

            - name: Setup
              run: |
                  mkdir -v -p ~/.local/share/godot/templates
                  mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

            - name: Testing
              run: |
                  godot --headless -v -e -q --path . -s addons/gut/gut_cmdln.gd -gdir=res://scripts -gsuffix=.test.gd -gprefix=
