name: "Godot Unit Tests"
on:
  push:
    paths:
      - "**.test.gd"
      - "**.tscn"
      - "**.gd"
      - "**.yml"

jobs:
  execute-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Godot
        run: godot --headless --import

      - name: Testing
        run: |
          godot --headless -v -e --quit -s res://addons/gut/gut_cmdln.gd -gdir=res://scripts -gsuffix=.test.gd -gprefix=
