name: "Godot Unit Tests"
on:
  push:
    paths:
      - "**.test.gd"
      - "**.tscn"
      - "**.gd"
      - "**.yml"

jobs:
  execute-tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Testing
        uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: "4.2.2"
          version: "v4.3.3"
          paths: |
            res://scripts/
          timeout: 5
          report-name: test_report.xml
